"""
VoxStory — exporters/docx_exporter.py

Converts VoxStory markdown output into a formatted .docx file
ready to be shared with clients or pasted into Confluence.
"""

import io
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def markdown_to_docx(markdown_text: str, mode: str = "Transcript") -> bytes:
    """
    Converts VoxStory markdown output to a formatted Word document.

    Args:
        markdown_text: The raw markdown string returned by the agent
        mode: "Transcript" or "Refinement" — used in the document title

    Returns:
        Bytes of the .docx file, ready for Streamlit download
    """
    doc = Document()

    # ── Document title ──────────────────────────────────────────────
    title = doc.add_heading("VoxStory — Agile Artifact Output", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.runs[0]
    title_run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

    subtitle = doc.add_paragraph(f"Mode: {mode} Analysis")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.color.rgb = RGBColor(0x55, 0x55, 0x55)
    subtitle.runs[0].font.italic = True

    doc.add_paragraph()  # spacer

    # ── Parse and render markdown lines ─────────────────────────────
    lines = markdown_text.split("\n")

    for line in lines:
        stripped = line.strip()

        if not stripped:
            doc.add_paragraph()  # blank line / spacer
            continue

        # H2 headings (## Story N: Title)
        if stripped.startswith("## "):
            heading = doc.add_heading(stripped[3:], level=2)
            heading.runs[0].font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

        # H3 headings (### Section)
        elif stripped.startswith("### "):
            heading = doc.add_heading(stripped[4:], level=3)
            heading.runs[0].font.color.rgb = RGBColor(0x2D, 0x6A, 0x4F)

        # Horizontal rule
        elif stripped == "---":
            doc.add_paragraph("─" * 60)

        # Bold labels (**Label:** value)
        elif stripped.startswith("**") and ":**" in stripped:
            para = doc.add_paragraph()
            # Split on first :** to separate label from value
            parts = stripped.split(":**", 1)
            label = parts[0].replace("**", "").strip()
            value = parts[1].strip() if len(parts) > 1 else ""

            run_label = para.add_run(f"{label}: ")
            run_label.bold = True
            run_label.font.size = Pt(11)

            if value:
                run_value = para.add_run(value)
                run_value.font.size = Pt(11)

        # Italic lines (*text*)
        elif stripped.startswith("*") and stripped.endswith("*") and len(stripped) > 2:
            para = doc.add_paragraph()
            run = para.add_run(stripped.strip("*"))
            run.italic = True
            run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)

        # Checkbox items (- [ ] text)
        elif stripped.startswith("- [ ]"):
            para = doc.add_paragraph(style="List Bullet")
            para.add_run(f"☐ {stripped[5:].strip()}")

        # Checked items (- [x] text)
        elif stripped.startswith("- [x]"):
            para = doc.add_paragraph(style="List Bullet")
            para.add_run(f"☑ {stripped[5:].strip()}")

        # Bullet points (- text)
        elif stripped.startswith("- "):
            para = doc.add_paragraph(style="List Bullet")
            para.add_run(stripped[2:])

        # Numbered list (1. text)
        elif len(stripped) > 2 and stripped[0].isdigit() and stripped[1] == ".":
            para = doc.add_paragraph(style="List Number")
            para.add_run(stripped[2:].strip())

        # Regular paragraph
        else:
            doc.add_paragraph(stripped)

    # ── Footer ───────────────────────────────────────────────────────
    doc.add_paragraph()
    footer = doc.add_paragraph("Generated by VoxStory — AI-Powered BA Assistant")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    footer.runs[0].font.italic = True
    footer.runs[0].font.size = Pt(9)

    # ── Write to bytes ───────────────────────────────────────────────
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()
