[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
font = "sans serif"
primaryColor = "#0052CC"
backgroundColor = "#F4F5F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B4D"
